spring:
  application:
    name: shopping-cart

cart:
  threadsPool: 5
  tasks:
    payments:
      frecuency: 5 #minutes
---
spring:
  profiles: local, test
  data:
    mongodb:
      database: test-db

server:
  port: 8888

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
